---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": "*"
license_file: LICENSE
name: frr
namespace: frr
readme: README.rst
repository: https://github.com/ansible-collections/frr
